### ISSUE TITLE
Enable Custom Metadata

### ISSUE THREAD

**Issue by knoppiks** [nfdi4health/lap-deployment#1]

**Comment by beanformer** [comment]
and provide a possibility or workflow to add self-de veloped metadata schemes.

**Comment by fmeineke** [comment]
Extended Metadata is enabled. MDS 3.3. included. Self-de veloped metadata schemes are in the roadmap to main branch - en/disable manager already  in server admin.

**Comment by beanformer** [comment]
Is it possible to add self-defined MDS in SEEK via the admin panel?
