### ISSUE TITLE
docker-compose with hyphen

### ISSUE THREAD

**Issue by fmeineke** [nfdi4health/lap-deployment#4]
better replace in readme
`docker compose up -d`
by
`docker-compose up-d`
which is more compatible; in my setting this was an unneccessary stumbling block

**Comment by beanformer** [comment]
I think these two commands are not the same, the first one is the more current approach, but the latter one has more features.

BTW: There should be a space between up and -d.

**Comment by fmeineke** [comment]
Ok, now it worked for me as well (updates? misoperation?). Whereby docker-compose also worked.
