### ISSUE TITLE
Nutzerregistrierung schlägt fehl wegen fehlendem Rewrite

### ISSUE THREAD

**Issue by beanformer** [nfdi4health/lap-deployment#5]
Wenn man unter [www.health-atlas.de](http://www.health-atlas.de/) -> "Navigate" (links unten) -> "Login" klickt, führt das zu https://www.health-atlas.de/login und dort unter der Login-Maske gibt es den Link „Need an account“.

Der führt leider auf [http://localhost:3000/signup](http://localhost:3000/signup). Hier haben wir einen kleinen Bug, offensichtlich wird die URL durch den Proxy nicht richtig übersetzt.

Ich gebe zu, dass es eine Nutzermeldung war, mir selbst ist es nicht aufgefallen.

**Comment by knoppiks** [comment]
Falscher Server
health-atlas.de nutzt meines Wissens nach nicht dieses lap-deployment.
/cc @ChristophB
